### ISSUE TITLE
Widget text can become invisible

### ISSUE THREAD

**Issue by rparkins999** [rparkins999/AndroidSecondsClockWidget#12]
To reproduce the problem, open the app, select Configure new widget, then Set widget background colour. Move the value and opacity sliders to 255: this sets the background colour to white. Select Done and then Set widget text colour. Move the value sliders to 0: this sets the text colour to black. The preview now shows black text on a white background. Select Done and then Set widget text colour again. The text is no longer visible. It doesn't seem to be possible to make the text visible again without deinstalling and reinstalling the app.

If you set the background and text colours by moving the three colour sliders, it seems to work normally, so it looks as if the problem is in the HSV to RGB conversion.

**Comment by rparkins999** [comment]
Fixed by release 2.4

**Comment by THEtomaso** [comment]
> Fixed by release 2.4

Confirmed! 😃 

Thanks for your quick and good service in this matter, rparkins999.
I've been looking for a clock to replace the stock app, for quite a while, and now it appears that I've finally found it!
Keep up the good work!! 👍

**Comment by rparkins999** [comment]
Thanks for your support. However I would have fixed it even faster if you had described what you did (set the Value slider on the widget text colour configuration page to zero) and what happened that shouldn't have happened (widget text became invisible on a light home screen background), instead of attaching it to a closed issue that you may have thought was similar, but had a totally different cause.

If you had set the red, green, and blue sliders to zero (the way that I would normally use to set the widget text colour to black), it would have worked correctly, since the problem was in the HSV to RGB conversion, which is only used if you explicitly set the Hue, Saturation, or Value.

When reporting a problem with software, it's always better to specify exactly what you did to reproduce it (if it is reproducible), and exactly how it misbehaved as a result.
